values:
  database:
    user: # database.user
    password: # database.password
    name: # database.dbname
    host: # database.host
    port: # database.port

  workspace:
    root: # workspace.root
    wikipedia: # workspace.wikipedia
    resource: # workspace.resource

  server:
      host: # server.host
      port: # server.port

  log:
    level: # log.level
    path: # log.path

environments:
  database:
    user: ERICA_DATABASE_USER
    password: ERICA_DATABASE_PASSWORD
    name: ERICA_DATABASE_DBNAME
    host: ERICA_DATABASE_HOST
    port: ERICA_DATABASE_PORT

  workspace:
    root: ERICA_WORKSPACE_ROOT
    wikipedia: ERICA_WORKSPACE_WIKIPEDIA
    resource: ERICA_WORKSPACE_RESOURCE

  server:
    host: ERICA_SERVER_HOST
    port: ERICA_SERVER_PORT

  log:
    level: ERICA_LOG_LEVEL
    path: ERICA_LOG_PATH
