extra_titles = [
    "メディア",
    "特別",
    "ノート",
    "利用者",
    "利用者‐会話",
    "Wikipedia",
    "Wikipedia‐ノート",
    "ファイル",
    "ファイル‐ノート",
    "MediaWiki",
    "MediaWiki‐ノート",
    "Template",
    "Template‐ノート",
    "Help",
    "Help‐ノート",
    "Category",
    "Category‐ノート",
    "Portal",
    "Portal‐ノート",
    "プロジェクト",
    "プロジェクト‐ノート",
    "モジュール",
    "モジュール‐ノート",
    "Gadget",
    "Gadget talk",
    "Gadget definition",
    "Gadget definition talk",
    "Topic",
]

extra_titles_en = [
    "Media",
    "Special",
    "Talk",
    "User",
    "User talk",
    "Wikipedia",
    "Wikipedia talk",
    "File",
    "File talk",
    "MediaWiki",
    "MediaWiki talk",
    "Template",
    "Template talk",
    "Help",
    "Help talk",
    "Category",
    "Category talk",
    "Portal",
    "Portal talk",
    "Book",
    "Book talk",
    "Draft",
    "Draft talk",
    "Education Program",
    "Education Program talk",
    "TimedText",
    "TimedText talk",
    "Module",
    "Module talk",
    "Image"
]
